### ISSUE TITLE
Petit problème d'encodage des caractères spéciaux

### ISSUE THREAD

**Issue by Gnomme** [ishtarimu/MicroMicroBlog#1]
A voir ici  : http://porteguillau.me/blog/#1472996107

**Comment by ishtarimu** [comment]
Ca doit venir du navigateur. Je vais faire des tests yo.

**Comment by ishtarimu** [comment]
tu mets à jour et tu retests :)

**Comment by Gnomme** [comment]
ok ça fonctionne mieux sur les caractères spéciaux type @ ( [ etc.
Par contre tj un souci sur les ' et "
J'ai testé en ajoutant stripslashes ce qui semble fonctionner : `stripslashes(mb_convert_encoding($_POST['titre'], "UTF-8"))`
`stripslashes(mb_convert_encoding($_POST['txt'], "UTF-8"))`

selon les dires de certains, cela peut venir de la fonction magic_quote  
[http://stackoverflow.com/questions/6324614/php-why-do-you-escape-my-quotes](url)

Mais du coup add.php a pris 33ko... on est foutus

**Comment by ishtarimu** [comment]
33ko wtf ! Même en passant mes journées le cul sur une chaise j'ai pas autant grossi. 
Je commit ça vendredi.

**Comment by Gnomme** [comment]
le lard stun art.
Jvais regarder pour ajouter une microfonction d'édition des posts si ça te botte

**Comment by ishtarimu** [comment]
Ouais! Tu fais une branche?
